version: "3.3"
services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_VERSION:-9.6.16}
    container_name: friends_postgres
    ports:
    - "5433:5432"
    environment:
    - POSTGRES_DB=db_friends
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    - DB_HOST=127.0.0.1
    - DB_PORT=5432
    volumes:
    - ./postgres/init.sql:/docker-entrypoint-initdb.d/postgres.sql
